### ISSUE TITLE
Error: Could not parse JSON (lexical error: invalid char in json text.)

### ISSUE THREAD

**Issue by Panagiss** [Tazeg/i3status#2]
Hi,

I have few problems with your script. At first the bar is missing few fields. It looks like this:
![image](https://user-images.githubusercontent.com/56695201/141330913-006f372f-516b-4f78-a314-8289795d0c9c.png)

After calendar(and the other icons on the right) click event it will show this error:
![image](https://user-images.githubusercontent.com/56695201/141331137-47060d20-02c0-466b-ab24-e019f6a87610.png)

**Comment by Tazeg** [comment]
Hello, I suppose some scripts are not working correctly. You should try them one by one, for example : 

```
cd ~/.config/i3status/
./cpu.py
./disk.py
# ... and sh scripts
```

You should get some interesting errors.

**Comment by Panagiss** [comment]
The problem was that I specified relative and not full paths in both the I3 config file and also into the my_bar.sh
Also you should note in the .md there are hardcoded paths that must be changed in the the my_bar.sh 

Lastly i wanted to ask.... I changed the internval (sleep) from 10 to 1 and it did refresh at 5 seconds. Is there something i'm missing?
Thanks

**Comment by Tazeg** [comment]
Thanks for the suggestion. The README is updated.

There are some APIs : meteo, crypto values, IP address... I guess there is latency and all answers are not done in 1 second. And it is too much requests for thoses API. You may get "403 too many requests" from them. Your IP address, the weather are not changing each second. So you should disable some. Or find a way to set a refresh time for each script. Or stay at 10 seconds.
